// 자동 생성 파일 — 직접 수정하지 마세요.
// 원본: design/maps/*-districts.svg, *-cities.svg, sejong-towns.svg (design/maps/SOURCES.md 참고)
// 재생성: node design/maps/source/svg_to_ts.mjs

import type { ProvinceMapEntry } from "@/types/explore";

// 시·도 id → 상세 지도 (path 좌표가 들어 있는 지도 데이터는 load()로 필요할 때만 불러온다)
export const PROVINCE_MAPS: Record<string, ProvinceMapEntry> = {
  "seoul": {
    contentBox: {"x":12,"y":12,"width":366,"height":299.92},
    regions: [
      {"id":"jongno","nameKo":"종로구","code":"11110"},
      {"id":"jung","nameKo":"중구","code":"11140"},
      {"id":"yongsan","nameKo":"용산구","code":"11170"},
      {"id":"seongdong","nameKo":"성동구","code":"11200"},
      {"id":"gwangjin","nameKo":"광진구","code":"11215"},
      {"id":"dongdaemun","nameKo":"동대문구","code":"11230"},
      {"id":"jungnang","nameKo":"중랑구","code":"11260"},
      {"id":"seongbuk","nameKo":"성북구","code":"11290"},
      {"id":"gangbuk","nameKo":"강북구","code":"11305"},
      {"id":"dobong","nameKo":"도봉구","code":"11320"},
      {"id":"nowon","nameKo":"노원구","code":"11350"},
      {"id":"eunpyeong","nameKo":"은평구","code":"11380"},
      {"id":"seodaemun","nameKo":"서대문구","code":"11410"},
      {"id":"mapo","nameKo":"마포구","code":"11440"},
      {"id":"yangcheon","nameKo":"양천구","code":"11470"},
      {"id":"gangseo","nameKo":"강서구","code":"11500"},
      {"id":"guro","nameKo":"구로구","code":"11530"},
      {"id":"geumcheon","nameKo":"금천구","code":"11545"},
      {"id":"yeongdeungpo","nameKo":"영등포구","code":"11560"},
      {"id":"dongjak","nameKo":"동작구","code":"11590"},
      {"id":"gwanak","nameKo":"관악구","code":"11620"},
      {"id":"seocho","nameKo":"서초구","code":"11650"},
      {"id":"gangnam","nameKo":"강남구","code":"11680"},
      {"id":"songpa","nameKo":"송파구","code":"11710"},
      {"id":"gangdong","nameKo":"강동구","code":"11740"},
    ],
    load: () => import("./seoulDistricts").then((m) => m.SEOUL_DISTRICTS_MAP),
  },
  "busan": {
    contentBox: {"x":12,"y":12,"width":366,"height":351.16},
    regions: [
      {"id":"jung","nameKo":"중구","code":"26110"},
      {"id":"seo","nameKo":"서구","code":"26140"},
      {"id":"dong","nameKo":"동구","code":"26170"},
      {"id":"yeongdo","nameKo":"영도구","code":"26200"},
      {"id":"busanjin","nameKo":"부산진구","code":"26230"},
      {"id":"dongnae","nameKo":"동래구","code":"26260"},
      {"id":"nam","nameKo":"남구","code":"26290"},
      {"id":"buk","nameKo":"북구","code":"26320"},
      {"id":"haeundae","nameKo":"해운대구","code":"26350"},
      {"id":"saha","nameKo":"사하구","code":"26380"},
      {"id":"geumjeong","nameKo":"금정구","code":"26410"},
      {"id":"gangseo","nameKo":"강서구","code":"26440"},
      {"id":"yeonje","nameKo":"연제구","code":"26470"},
      {"id":"suyeong","nameKo":"수영구","code":"26500"},
      {"id":"sasang","nameKo":"사상구","code":"26530"},
      {"id":"gijang","nameKo":"기장군","code":"26710"},
    ],
    load: () => import("./busanDistricts").then((m) => m.BUSAN_DISTRICTS_MAP),
  },
  "daegu": {
    contentBox: {"x":12,"y":12.01,"width":366,"height":592.48},
    regions: [
      {"id":"jung","nameKo":"중구","code":"27110"},
      {"id":"dong","nameKo":"동구","code":"27140"},
      {"id":"seo","nameKo":"서구","code":"27170"},
      {"id":"nam","nameKo":"남구","code":"27200"},
      {"id":"buk","nameKo":"북구","code":"27230"},
      {"id":"suseong","nameKo":"수성구","code":"27260"},
      {"id":"dalseo","nameKo":"달서구","code":"27290"},
      {"id":"dalseong","nameKo":"달성군","code":"27710"},
      {"id":"gunwi","nameKo":"군위군","code":"27720"},
    ],
    load: () => import("./daeguDistricts").then((m) => m.DAEGU_DISTRICTS_MAP),
  },
  "incheon": {
    contentBox: {"x":12,"y":12,"width":365.99,"height":405.9},
    regions: [
      {"id":"jemulpo","nameKo":"제물포구","code":"28125"},
      {"id":"yeongjong","nameKo":"영종구","code":"28155"},
      {"id":"michuhol","nameKo":"미추홀구","code":"28177"},
      {"id":"yeonsu","nameKo":"연수구","code":"28185"},
      {"id":"namdong","nameKo":"남동구","code":"28200"},
      {"id":"bupyeong","nameKo":"부평구","code":"28237"},
      {"id":"gyeyang","nameKo":"계양구","code":"28245"},
      {"id":"seohae","nameKo":"서해구","code":"28275"},
      {"id":"geomdan","nameKo":"검단구","code":"28290"},
      {"id":"ganghwa","nameKo":"강화군","code":"28710"},
      {"id":"ongjin","nameKo":"옹진군","code":"28720"},
    ],
    load: () => import("./incheonDistricts").then((m) => m.INCHEON_DISTRICTS_MAP),
  },
  "daejeon": {
    contentBox: {"x":12,"y":12,"width":366,"height":464.26},
    regions: [
      {"id":"dong","nameKo":"동구","code":"30110"},
      {"id":"jung","nameKo":"중구","code":"30140"},
      {"id":"seo","nameKo":"서구","code":"30170"},
      {"id":"yuseong","nameKo":"유성구","code":"30200"},
      {"id":"daedeok","nameKo":"대덕구","code":"30230"},
    ],
    load: () => import("./daejeonDistricts").then((m) => m.DAEJEON_DISTRICTS_MAP),
  },
  "ulsan": {
    contentBox: {"x":12,"y":12,"width":366,"height":359.57},
    regions: [
      {"id":"jung","nameKo":"중구","code":"31110"},
      {"id":"nam","nameKo":"남구","code":"31140"},
      {"id":"dong","nameKo":"동구","code":"31170"},
      {"id":"buk","nameKo":"북구","code":"31200"},
      {"id":"ulju","nameKo":"울주군","code":"31710"},
    ],
    load: () => import("./ulsanDistricts").then((m) => m.ULSAN_DISTRICTS_MAP),
  },
  "sejong": {
    contentBox: {"x":12,"y":12,"width":366,"height":529.17},
    regions: [
      {"id":"jochiwon","nameKo":"조치원읍","code":"3611025000"},
      {"id":"yeongi","nameKo":"연기면","code":"3611031000"},
      {"id":"yeondong","nameKo":"연동면","code":"3611032000"},
      {"id":"bugang","nameKo":"부강면","code":"3611033000"},
      {"id":"geumnam","nameKo":"금남면","code":"3611034000"},
      {"id":"janggun","nameKo":"장군면","code":"3611035000"},
      {"id":"yeonseo","nameKo":"연서면","code":"3611036000"},
      {"id":"jeonui","nameKo":"전의면","code":"3611037000"},
      {"id":"jeondong","nameKo":"전동면","code":"3611038000"},
      {"id":"sojeong","nameKo":"소정면","code":"3611039000"},
      {"id":"hansol","nameKo":"한솔동","code":"3611051000"},
      {"id":"saerom","nameKo":"새롬동","code":"3611051500"},
      {"id":"naseong","nameKo":"나성동","code":"3611051800"},
      {"id":"dodam","nameKo":"도담동","code":"3611052000"},
      {"id":"eojin","nameKo":"어진동","code":"3611052300"},
      {"id":"haemil","nameKo":"해밀동","code":"3611052500"},
      {"id":"areum","nameKo":"아름동","code":"3611053000"},
      {"id":"jongchon","nameKo":"종촌동","code":"3611054000"},
      {"id":"goun","nameKo":"고운동","code":"3611055000"},
      {"id":"sodam","nameKo":"소담동","code":"3611055500"},
      {"id":"bangok","nameKo":"반곡동","code":"3611055600"},
      {"id":"boram","nameKo":"보람동","code":"3611056000"},
      {"id":"daepyeong","nameKo":"대평동","code":"3611057000"},
      {"id":"dajeong","nameKo":"다정동","code":"3611058000"},
    ],
    load: () => import("./sejongTowns").then((m) => m.SEJONG_TOWNS_MAP),
  },
  "gyeonggi": {
    contentBox: {"x":12,"y":12,"width":365.99,"height":439.54},
    regions: [
      {"id":"suwon","nameKo":"수원시","code":"41110"},
      {"id":"seongnam","nameKo":"성남시","code":"41130"},
      {"id":"uijeongbu","nameKo":"의정부시","code":"41150"},
      {"id":"anyang","nameKo":"안양시","code":"41170"},
      {"id":"bucheon","nameKo":"부천시","code":"41190"},
      {"id":"gwangmyeong","nameKo":"광명시","code":"41210"},
      {"id":"pyeongtaek","nameKo":"평택시","code":"41220"},
      {"id":"dongducheon","nameKo":"동두천시","code":"41250"},
      {"id":"ansan","nameKo":"안산시","code":"41270"},
      {"id":"goyang","nameKo":"고양시","code":"41280"},
      {"id":"gwacheon","nameKo":"과천시","code":"41290"},
      {"id":"guri","nameKo":"구리시","code":"41310"},
      {"id":"namyangju","nameKo":"남양주시","code":"41360"},
      {"id":"osan","nameKo":"오산시","code":"41370"},
      {"id":"siheung","nameKo":"시흥시","code":"41390"},
      {"id":"gunpo","nameKo":"군포시","code":"41410"},
      {"id":"uiwang","nameKo":"의왕시","code":"41430"},
      {"id":"hanam","nameKo":"하남시","code":"41450"},
      {"id":"yongin","nameKo":"용인시","code":"41460"},
      {"id":"paju","nameKo":"파주시","code":"41480"},
      {"id":"icheon","nameKo":"이천시","code":"41500"},
      {"id":"anseong","nameKo":"안성시","code":"41550"},
      {"id":"gimpo","nameKo":"김포시","code":"41570"},
      {"id":"hwaseong","nameKo":"화성시","code":"41590"},
      {"id":"gwangju","nameKo":"광주시","code":"41610"},
      {"id":"yangju","nameKo":"양주시","code":"41630"},
      {"id":"pocheon","nameKo":"포천시","code":"41650"},
      {"id":"yeoju","nameKo":"여주시","code":"41670"},
      {"id":"yeoncheon","nameKo":"연천군","code":"41800"},
      {"id":"gapyeong","nameKo":"가평군","code":"41820"},
      {"id":"yangpyeong","nameKo":"양평군","code":"41830"},
    ],
    load: () => import("./gyeonggiCities").then((m) => m.GYEONGGI_CITIES_MAP),
  },
  "gangwon": {
    contentBox: {"x":12,"y":12,"width":366,"height":326.47},
    regions: [
      {"id":"chuncheon","nameKo":"춘천시","code":"51110"},
      {"id":"wonju","nameKo":"원주시","code":"51130"},
      {"id":"gangneung","nameKo":"강릉시","code":"51150"},
      {"id":"donghae","nameKo":"동해시","code":"51170"},
      {"id":"taebaek","nameKo":"태백시","code":"51190"},
      {"id":"sokcho","nameKo":"속초시","code":"51210"},
      {"id":"samcheok","nameKo":"삼척시","code":"51230"},
      {"id":"hongcheon","nameKo":"홍천군","code":"51720"},
      {"id":"hoengseong","nameKo":"횡성군","code":"51730"},
      {"id":"yeongwol","nameKo":"영월군","code":"51750"},
      {"id":"pyeongchang","nameKo":"평창군","code":"51760"},
      {"id":"jeongseon","nameKo":"정선군","code":"51770"},
      {"id":"cheorwon","nameKo":"철원군","code":"51780"},
      {"id":"hwacheon","nameKo":"화천군","code":"51790"},
      {"id":"yanggu","nameKo":"양구군","code":"51800"},
      {"id":"inje","nameKo":"인제군","code":"51810"},
      {"id":"goseong","nameKo":"고성군","code":"51820"},
      {"id":"yangyang","nameKo":"양양군","code":"51830"},
    ],
    load: () => import("./gangwonCities").then((m) => m.GANGWON_CITIES_MAP),
  },
  "chungbuk": {
    contentBox: {"x":12,"y":12,"width":366,"height":413.36},
    regions: [
      {"id":"cheongju","nameKo":"청주시","code":"43110"},
      {"id":"chungju","nameKo":"충주시","code":"43130"},
      {"id":"jecheon","nameKo":"제천시","code":"43150"},
      {"id":"boeun","nameKo":"보은군","code":"43720"},
      {"id":"okcheon","nameKo":"옥천군","code":"43730"},
      {"id":"yeongdong","nameKo":"영동군","code":"43740"},
      {"id":"jeungpyeong","nameKo":"증평군","code":"43745"},
      {"id":"jincheon","nameKo":"진천군","code":"43750"},
      {"id":"goesan","nameKo":"괴산군","code":"43760"},
      {"id":"eumseong","nameKo":"음성군","code":"43770"},
      {"id":"danyang","nameKo":"단양군","code":"43800"},
    ],
    load: () => import("./chungbukCities").then((m) => m.CHUNGBUK_CITIES_MAP),
  },
  "chungnam": {
    contentBox: {"x":12,"y":12,"width":365.99,"height":291.88},
    regions: [
      {"id":"cheonan","nameKo":"천안시","code":"44130"},
      {"id":"gongju","nameKo":"공주시","code":"44150"},
      {"id":"boryeong","nameKo":"보령시","code":"44180"},
      {"id":"asan","nameKo":"아산시","code":"44200"},
      {"id":"seosan","nameKo":"서산시","code":"44210"},
      {"id":"nonsan","nameKo":"논산시","code":"44230"},
      {"id":"gyeryong","nameKo":"계룡시","code":"44250"},
      {"id":"dangjin","nameKo":"당진시","code":"44270"},
      {"id":"geumsan","nameKo":"금산군","code":"44710"},
      {"id":"buyeo","nameKo":"부여군","code":"44760"},
      {"id":"seocheon","nameKo":"서천군","code":"44770"},
      {"id":"cheongyang","nameKo":"청양군","code":"44790"},
      {"id":"hongseong","nameKo":"홍성군","code":"44800"},
      {"id":"yesan","nameKo":"예산군","code":"44810"},
      {"id":"taean","nameKo":"태안군","code":"44825"},
    ],
    load: () => import("./chungnamCities").then((m) => m.CHUNGNAM_CITIES_MAP),
  },
  "jeonbuk": {
    contentBox: {"x":12,"y":12,"width":366,"height":213.21},
    regions: [
      {"id":"jeonju","nameKo":"전주시","code":"52110"},
      {"id":"gunsan","nameKo":"군산시","code":"52130"},
      {"id":"iksan","nameKo":"익산시","code":"52140"},
      {"id":"jeongeup","nameKo":"정읍시","code":"52180"},
      {"id":"namwon","nameKo":"남원시","code":"52190"},
      {"id":"gimje","nameKo":"김제시","code":"52210"},
      {"id":"wanju","nameKo":"완주군","code":"52710"},
      {"id":"jinan","nameKo":"진안군","code":"52720"},
      {"id":"muju","nameKo":"무주군","code":"52730"},
      {"id":"jangsu","nameKo":"장수군","code":"52740"},
      {"id":"imsil","nameKo":"임실군","code":"52750"},
      {"id":"sunchang","nameKo":"순창군","code":"52770"},
      {"id":"gochang","nameKo":"고창군","code":"52790"},
      {"id":"buan","nameKo":"부안군","code":"52800"},
    ],
    load: () => import("./jeonbukCities").then((m) => m.JEONBUK_CITIES_MAP),
  },
  "jeonnam-gwangju": {
    contentBox: {"x":12,"y":12,"width":366,"height":395.6},
    regions: [
      {"id":"mokpo","nameKo":"목포시","code":"12110"},
      {"id":"yeosu","nameKo":"여수시","code":"12130"},
      {"id":"suncheon","nameKo":"순천시","code":"12150"},
      {"id":"naju","nameKo":"나주시","code":"12170"},
      {"id":"gwangyang","nameKo":"광양시","code":"12190"},
      {"id":"dong","nameKo":"동구","code":"12210"},
      {"id":"seo","nameKo":"서구","code":"12240"},
      {"id":"nam","nameKo":"남구","code":"12270"},
      {"id":"buk","nameKo":"북구","code":"12300"},
      {"id":"gwangsan","nameKo":"광산구","code":"12330"},
      {"id":"damyang","nameKo":"담양군","code":"12710"},
      {"id":"gokseong","nameKo":"곡성군","code":"12720"},
      {"id":"gurye","nameKo":"구례군","code":"12730"},
      {"id":"goheung","nameKo":"고흥군","code":"12740"},
      {"id":"boseong","nameKo":"보성군","code":"12750"},
      {"id":"hwasun","nameKo":"화순군","code":"12760"},
      {"id":"jangheung","nameKo":"장흥군","code":"12770"},
      {"id":"gangjin","nameKo":"강진군","code":"12780"},
      {"id":"haenam","nameKo":"해남군","code":"12790"},
      {"id":"yeongam","nameKo":"영암군","code":"12800"},
      {"id":"muan","nameKo":"무안군","code":"12810"},
      {"id":"hampyeong","nameKo":"함평군","code":"12820"},
      {"id":"yeonggwang","nameKo":"영광군","code":"12830"},
      {"id":"jangseong","nameKo":"장성군","code":"12840"},
      {"id":"wando","nameKo":"완도군","code":"12850"},
      {"id":"jindo","nameKo":"진도군","code":"12860"},
      {"id":"sinan","nameKo":"신안군","code":"12870"},
    ],
    load: () => import("./jeonnamGwangjuCities").then((m) => m.JEONNAM_GWANGJU_CITIES_MAP),
  },
  "gyeongbuk": {
    contentBox: {"x":12,"y":12,"width":366,"height":401.84},
    regions: [
      {"id":"pohang","nameKo":"포항시","code":"47110"},
      {"id":"gyeongju","nameKo":"경주시","code":"47130"},
      {"id":"gimcheon","nameKo":"김천시","code":"47150"},
      {"id":"andong","nameKo":"안동시","code":"47170"},
      {"id":"gumi","nameKo":"구미시","code":"47190"},
      {"id":"yeongju","nameKo":"영주시","code":"47210"},
      {"id":"yeongcheon","nameKo":"영천시","code":"47230"},
      {"id":"sangju","nameKo":"상주시","code":"47250"},
      {"id":"mungyeong","nameKo":"문경시","code":"47280"},
      {"id":"gyeongsan","nameKo":"경산시","code":"47290"},
      {"id":"uiseong","nameKo":"의성군","code":"47730"},
      {"id":"cheongsong","nameKo":"청송군","code":"47750"},
      {"id":"yeongyang","nameKo":"영양군","code":"47760"},
      {"id":"yeongdeok","nameKo":"영덕군","code":"47770"},
      {"id":"cheongdo","nameKo":"청도군","code":"47820"},
      {"id":"goryeong","nameKo":"고령군","code":"47830"},
      {"id":"seongju","nameKo":"성주군","code":"47840"},
      {"id":"chilgok","nameKo":"칠곡군","code":"47850"},
      {"id":"yecheon","nameKo":"예천군","code":"47900"},
      {"id":"bonghwa","nameKo":"봉화군","code":"47920"},
      {"id":"uljin","nameKo":"울진군","code":"47930"},
      {"id":"ulleung","nameKo":"울릉군","code":"47940"},
    ],
    load: () => import("./gyeongbukCities").then((m) => m.GYEONGBUK_CITIES_MAP),
  },
  "gyeongnam": {
    contentBox: {"x":12,"y":12,"width":366,"height":375.4},
    regions: [
      {"id":"changwon","nameKo":"창원시","code":"48120"},
      {"id":"jinju","nameKo":"진주시","code":"48170"},
      {"id":"tongyeong","nameKo":"통영시","code":"48220"},
      {"id":"sacheon","nameKo":"사천시","code":"48240"},
      {"id":"gimhae","nameKo":"김해시","code":"48250"},
      {"id":"miryang","nameKo":"밀양시","code":"48270"},
      {"id":"geoje","nameKo":"거제시","code":"48310"},
      {"id":"yangsan","nameKo":"양산시","code":"48330"},
      {"id":"uiryeong","nameKo":"의령군","code":"48720"},
      {"id":"haman","nameKo":"함안군","code":"48730"},
      {"id":"changnyeong","nameKo":"창녕군","code":"48740"},
      {"id":"goseong","nameKo":"고성군","code":"48820"},
      {"id":"namhae","nameKo":"남해군","code":"48840"},
      {"id":"hadong","nameKo":"하동군","code":"48850"},
      {"id":"sancheong","nameKo":"산청군","code":"48860"},
      {"id":"hamyang","nameKo":"함양군","code":"48870"},
      {"id":"geochang","nameKo":"거창군","code":"48880"},
      {"id":"hapcheon","nameKo":"합천군","code":"48890"},
    ],
    load: () => import("./gyeongnamCities").then((m) => m.GYEONGNAM_CITIES_MAP),
  },
  "jeju": {
    contentBox: {"x":12,"y":12,"width":366,"height":240.6},
    regions: [
      {"id":"jeju","nameKo":"제주시","code":"50110"},
      {"id":"seogwipo","nameKo":"서귀포시","code":"50130"},
    ],
    load: () => import("./jejuCities").then((m) => m.JEJU_CITIES_MAP),
  },
};
